# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import pet_adoption_pb2 as pet__adoption__pb2

GRPC_GENERATED_VERSION = '1.67.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in pet_adoption_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PetAdoptionServiceStub(object):
    """The service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterPet = channel.unary_unary(
                '/petadoption.PetAdoptionService/RegisterPet',
                request_serializer=pet__adoption__pb2.PetInfo.SerializeToString,
                response_deserializer=pet__adoption__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.SearchPet = channel.unary_unary(
                '/petadoption.PetAdoptionService/SearchPet',
                request_serializer=pet__adoption__pb2.SearchRequest.SerializeToString,
                response_deserializer=pet__adoption__pb2.SearchResponse.FromString,
                _registered_method=True)


class PetAdoptionServiceServicer(object):
    """The service definition
    """

    def RegisterPet(self, request, context):
        """Registers a new pet
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchPet(self, request, context):
        """Searches for a pet based on name, breed, or gender
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PetAdoptionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterPet': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterPet,
                    request_deserializer=pet__adoption__pb2.PetInfo.FromString,
                    response_serializer=pet__adoption__pb2.RegisterResponse.SerializeToString,
            ),
            'SearchPet': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchPet,
                    request_deserializer=pet__adoption__pb2.SearchRequest.FromString,
                    response_serializer=pet__adoption__pb2.SearchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'petadoption.PetAdoptionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('petadoption.PetAdoptionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PetAdoptionService(object):
    """The service definition
    """

    @staticmethod
    def RegisterPet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/petadoption.PetAdoptionService/RegisterPet',
            pet__adoption__pb2.PetInfo.SerializeToString,
            pet__adoption__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchPet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/petadoption.PetAdoptionService/SearchPet',
            pet__adoption__pb2.SearchRequest.SerializeToString,
            pet__adoption__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
